// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/business/v1/business.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateReplyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReplyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateReplyRequestMultiError, or nil if none found.
func (m *CreateReplyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReplyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReviewId

	// no validation rules for StoreId

	// no validation rules for Content

	// no validation rules for PicInfo

	// no validation rules for VideoInfo

	if len(errors) > 0 {
		return CreateReplyRequestMultiError(errors)
	}

	return nil
}

// CreateReplyRequestMultiError is an error wrapping multiple validation errors
// returned by CreateReplyRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateReplyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReplyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReplyRequestMultiError) AllErrors() []error { return m }

// CreateReplyRequestValidationError is the validation error returned by
// CreateReplyRequest.Validate if the designated constraints aren't met.
type CreateReplyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReplyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReplyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReplyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReplyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReplyRequestValidationError) ErrorName() string {
	return "CreateReplyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReplyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReplyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReplyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReplyRequestValidationError{}

// Validate checks the field values on CreateReplyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateReplyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateReplyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateReplyResponseMultiError, or nil if none found.
func (m *CreateReplyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateReplyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReplyId

	if len(errors) > 0 {
		return CreateReplyResponseMultiError(errors)
	}

	return nil
}

// CreateReplyResponseMultiError is an error wrapping multiple validation
// errors returned by CreateReplyResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateReplyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateReplyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateReplyResponseMultiError) AllErrors() []error { return m }

// CreateReplyResponseValidationError is the validation error returned by
// CreateReplyResponse.Validate if the designated constraints aren't met.
type CreateReplyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateReplyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateReplyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateReplyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateReplyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateReplyResponseValidationError) ErrorName() string {
	return "CreateReplyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateReplyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateReplyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateReplyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateReplyResponseValidationError{}
