// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/consumer/v1/consumer.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateConsumerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateConsumerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateConsumerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateConsumerRequestMultiError, or nil if none found.
func (m *CreateConsumerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateConsumerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for OrderId

	// no validation rules for StoreId

	if utf8.RuneCountInString(m.GetContent()) < 10 {
		err := CreateConsumerRequestValidationError{
			field:  "Content",
			reason: "value length must be at least 10 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_CreateConsumerRequest_PicInfo_Pattern.MatchString(m.GetPicInfo()) {
		err := CreateConsumerRequestValidationError{
			field:  "PicInfo",
			reason: "value does not match regex pattern \"^(http|https)://.+$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_CreateConsumerRequest_VideoInfo_Pattern.MatchString(m.GetVideoInfo()) {
		err := CreateConsumerRequestValidationError{
			field:  "VideoInfo",
			reason: "value does not match regex pattern \"^(http|https)://.+$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetScore(); val <= 0 || val > 5 {
		err := CreateConsumerRequestValidationError{
			field:  "Score",
			reason: "value must be inside range (0, 5]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetServiceScore(); val <= 0 || val > 5 {
		err := CreateConsumerRequestValidationError{
			field:  "ServiceScore",
			reason: "value must be inside range (0, 5]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetExpressScore(); val <= 0 || val > 5 {
		err := CreateConsumerRequestValidationError{
			field:  "ExpressScore",
			reason: "value must be inside range (0, 5]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetAnonymous(); val < 0 || val > 1 {
		err := CreateConsumerRequestValidationError{
			field:  "Anonymous",
			reason: "value must be inside range [0, 1]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateConsumerRequestMultiError(errors)
	}

	return nil
}

// CreateConsumerRequestMultiError is an error wrapping multiple validation
// errors returned by CreateConsumerRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateConsumerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateConsumerRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateConsumerRequestMultiError) AllErrors() []error { return m }

// CreateConsumerRequestValidationError is the validation error returned by
// CreateConsumerRequest.Validate if the designated constraints aren't met.
type CreateConsumerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateConsumerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateConsumerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateConsumerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateConsumerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateConsumerRequestValidationError) ErrorName() string {
	return "CreateConsumerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateConsumerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateConsumerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateConsumerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateConsumerRequestValidationError{}

var _CreateConsumerRequest_PicInfo_Pattern = regexp.MustCompile("^(http|https)://.+$")

var _CreateConsumerRequest_VideoInfo_Pattern = regexp.MustCompile("^(http|https)://.+$")

// Validate checks the field values on CreateConsumerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateConsumerReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateConsumerReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateConsumerReplyMultiError, or nil if none found.
func (m *CreateConsumerReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateConsumerReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReviewId

	if len(errors) > 0 {
		return CreateConsumerReplyMultiError(errors)
	}

	return nil
}

// CreateConsumerReplyMultiError is an error wrapping multiple validation
// errors returned by CreateConsumerReply.ValidateAll() if the designated
// constraints aren't met.
type CreateConsumerReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateConsumerReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateConsumerReplyMultiError) AllErrors() []error { return m }

// CreateConsumerReplyValidationError is the validation error returned by
// CreateConsumerReply.Validate if the designated constraints aren't met.
type CreateConsumerReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateConsumerReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateConsumerReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateConsumerReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateConsumerReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateConsumerReplyValidationError) ErrorName() string {
	return "CreateConsumerReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateConsumerReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateConsumerReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateConsumerReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateConsumerReplyValidationError{}
