// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.1
// source: api/consumer/v1/consumer.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateConsumerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StoreId       int64                  `protobuf:"varint,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	PicInfo       string                 `protobuf:"bytes,5,opt,name=pic_info,json=picInfo,proto3" json:"pic_info,omitempty"`       // 图片
	VideoInfo     string                 `protobuf:"bytes,6,opt,name=video_info,json=videoInfo,proto3" json:"video_info,omitempty"` // 视频
	Score         int32                  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`                         // 1-5 星
	ServiceScore  int32                  `protobuf:"varint,8,opt,name=service_score,json=serviceScore,proto3" json:"service_score,omitempty"`
	ExpressScore  int32                  `protobuf:"varint,9,opt,name=express_score,json=expressScore,proto3" json:"express_score,omitempty"`
	Anonymous     int32                  `protobuf:"varint,10,opt,name=anonymous,proto3" json:"anonymous,omitempty"` // 是否匿名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConsumerRequest) Reset() {
	*x = CreateConsumerRequest{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConsumerRequest) ProtoMessage() {}

func (x *CreateConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConsumerRequest.ProtoReflect.Descriptor instead.
func (*CreateConsumerRequest) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateConsumerRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateConsumerRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateConsumerRequest) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *CreateConsumerRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateConsumerRequest) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *CreateConsumerRequest) GetVideoInfo() string {
	if x != nil {
		return x.VideoInfo
	}
	return ""
}

func (x *CreateConsumerRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CreateConsumerRequest) GetServiceScore() int32 {
	if x != nil {
		return x.ServiceScore
	}
	return 0
}

func (x *CreateConsumerRequest) GetExpressScore() int32 {
	if x != nil {
		return x.ExpressScore
	}
	return 0
}

func (x *CreateConsumerRequest) GetAnonymous() int32 {
	if x != nil {
		return x.Anonymous
	}
	return 0
}

type CreateConsumerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConsumerReply) Reset() {
	*x = CreateConsumerReply{}
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConsumerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConsumerReply) ProtoMessage() {}

func (x *CreateConsumerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_consumer_v1_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConsumerReply.ProtoReflect.Descriptor instead.
func (*CreateConsumerReply) Descriptor() ([]byte, []int) {
	return file_api_consumer_v1_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateConsumerReply) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

var File_api_consumer_v1_consumer_proto protoreflect.FileDescriptor

const file_api_consumer_v1_consumer_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/consumer/v1/consumer.proto\x12\x0fapi.consumer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xa5\x03\n" +
	"\x15CreateConsumerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x19\n" +
	"\bstore_id\x18\x03 \x01(\x03R\astoreId\x12!\n" +
	"\acontent\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\n" +
	"R\acontent\x125\n" +
	"\bpic_info\x18\x05 \x01(\tB\x1a\xfaB\x17r\x152\x13^(http|https)://.+$R\apicInfo\x129\n" +
	"\n" +
	"video_info\x18\x06 \x01(\tB\x1a\xfaB\x17r\x152\x13^(http|https)://.+$R\tvideoInfo\x12\x1f\n" +
	"\x05score\x18\a \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x05 \x00R\x05score\x12.\n" +
	"\rservice_score\x18\b \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x05 \x00R\fserviceScore\x12.\n" +
	"\rexpress_score\x18\t \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x05 \x00R\fexpressScore\x12'\n" +
	"\tanonymous\x18\n" +
	" \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x01(\x00R\tanonymous\"2\n" +
	"\x13CreateConsumerReply\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x03R\breviewId2\x88\x01\n" +
	"\bConsumer\x12|\n" +
	"\fCreateReview\x12&.api.consumer.v1.CreateConsumerRequest\x1a$.api.consumer.v1.CreateConsumerReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/consumer/v1/reviewB0\n" +
	"\x0fapi.consumer.v1P\x01Z\x1breview-c/api/consumer/v1;v1b\x06proto3"

var (
	file_api_consumer_v1_consumer_proto_rawDescOnce sync.Once
	file_api_consumer_v1_consumer_proto_rawDescData []byte
)

func file_api_consumer_v1_consumer_proto_rawDescGZIP() []byte {
	file_api_consumer_v1_consumer_proto_rawDescOnce.Do(func() {
		file_api_consumer_v1_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_consumer_v1_consumer_proto_rawDesc), len(file_api_consumer_v1_consumer_proto_rawDesc)))
	})
	return file_api_consumer_v1_consumer_proto_rawDescData
}

var file_api_consumer_v1_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_consumer_v1_consumer_proto_goTypes = []any{
	(*CreateConsumerRequest)(nil), // 0: api.consumer.v1.CreateConsumerRequest
	(*CreateConsumerReply)(nil),   // 1: api.consumer.v1.CreateConsumerReply
}
var file_api_consumer_v1_consumer_proto_depIdxs = []int32{
	0, // 0: api.consumer.v1.Consumer.CreateReview:input_type -> api.consumer.v1.CreateConsumerRequest
	1, // 1: api.consumer.v1.Consumer.CreateReview:output_type -> api.consumer.v1.CreateConsumerReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_consumer_v1_consumer_proto_init() }
func file_api_consumer_v1_consumer_proto_init() {
	if File_api_consumer_v1_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_consumer_v1_consumer_proto_rawDesc), len(file_api_consumer_v1_consumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_consumer_v1_consumer_proto_goTypes,
		DependencyIndexes: file_api_consumer_v1_consumer_proto_depIdxs,
		MessageInfos:      file_api_consumer_v1_consumer_proto_msgTypes,
	}.Build()
	File_api_consumer_v1_consumer_proto = out.File
	file_api_consumer_v1_consumer_proto_goTypes = nil
	file_api_consumer_v1_consumer_proto_depIdxs = nil
}
