// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 数据库错误
func IsGormBadErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GormBadErr.String() && e.Code == 500
}

// 数据库错误
func ErrorGormBadErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_GormBadErr.String(), fmt.Sprintf(format, args...))
}

// 订单重复评论错误
func IsOrderReviewReviewErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OrderReviewReviewErr.String() && e.Code == 500
}

// 订单重复评论错误
func ErrorOrderReviewReviewErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_OrderReviewReviewErr.String(), fmt.Sprintf(format, args...))
}
